import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header>
        <nav>
          <img src='' alt='' />
          <a href='/'>Home</a>
          <a href='/events'>Events</a>
          <a href='/about-us'>About us</a>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((event, idx) => {
          return (
            <a key={event.id + idx} href={`/events/${event.id}`}>
              <Image
                alt={event.title}
                width={200}
                height={100}
                src={event.image}
              />
              <h2> {event.title} </h2>
              <p>{event.description}</p>
            </a>
          );
        })}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import('./../data/data.json');
  return {
    props: {
      data: events_categories,
    },
  };
}
