import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header>
        <nav>
          <img src='' alt='' />
          <a href='/'>Home</a>
          <a href='/events'>Events</a>
          <a href='/about-us'>About us</a>
        </nav>
      </header>

      <main className={styles.main}>
        <div>
          <a href='#'></a>
          <img src='' alt='' />
          <h2>Events in London</h2>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ab,
            assumenda, nisi maiores explicabo ullam temporibus ut nihil
            dignissimos distinctio nemo quod quisquam incidunt suscipit
            accusantium, sint consequuntur quaerat maxime. Natus.
          </p>
        </div>
        <div>
          <a href='#'></a>
          <img src='' alt='' />
          <h2>Events in Canada</h2>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ab,
            assumenda, nisi maiores explicabo ullam temporibus ut nihil
            dignissimos distinctio nemo quod quisquam incidunt suscipit
            accusantium, sint consequuntur quaerat maxime. Natus.
          </p>
        </div>
        <div>
          <a href='#'></a>
          <img src='' alt='' />
          <h2>Events in China</h2>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ab,
            assumenda, nisi maiores explicabo ullam temporibus ut nihil
            dignissimos distinctio nemo quod quisquam incidunt suscipit
            accusantium, sint consequuntur quaerat maxime. Natus.
          </p>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import('./../data/data.json');
  return {
    props: {
      data: events_categories,
    },
  };
}
